# Generated by Django 2.2.7 on 2021-09-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_userinfo_information'),
        ('CororateInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.UserInfo'),
        ),
    ]
