# Generated by Django 2.1.4 on 2019-05-30 23:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='url')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=datetime.datetime(2019, 5, 30, 23, 41, 7, 598825), verbose_name='文章标题')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='文章标题')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='文章标题')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
