# Generated by Django 2.1.4 on 2019-05-04 03:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='商品信息')),
                ('detail', tinymce.models.HTMLField(verbose_name='商品详情')),
            ],
            options={
                'db_table': 'df_goods_test',
            },
        ),
    ]
