# Generated by Django 2.2.7 on 2021-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('body', models.TextField(null=True, verbose_name='主体内容')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='url')),
                ('date', models.CharField(max_length=255, null=True, verbose_name='时间')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='来源')),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
    ]
