# Generated by Django 2.2.7 on 2021-09-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210924_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='info',
            new_name='information',
        ),
    ]
